version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../envs/.env.dev
    command: >
      uv run gunicorn main:app
      --worker-class uvicorn_worker.UvicornWorker
      --bind 0.0.0.0:8000
      --workers 4
      --timeout 30
      --access-logfile -
      --error-logfile -
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pw123!
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pw123!
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:8.0
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


volumes:
  db_data:
  redis-data: